feat: support automatically translated messages
GetStream/stream-chat-react-native pull request #1400
Opened 2022-05-24 16:34 UTC by madsroskar

This PR is to be treated as a draft/not complete PR at the moment. The functionality works, but I've spent my last two brain cells trying to figure out all the different intentions of the code, so my refactoring is mostly just me parsing it piece by piece after writing some tests. 

To be completed.

2022-05-24 16:37 UTC, madsroskar commented on package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
> +  const mentionedUsersRegExp = new RegExp(`${mentionedUsers}|(!:${mentionedUsers})`, 'mg');
Note to self: the or here is unnecessary - can just be `mentionedUsers`

2022-05-24 19:09 UTC, vanGalilea requested changes

2022-05-25 08:27 UTC, madsroskar commented on examples/SampleApp/src/hooks/useChatClient.ts
> +      language: 'es' as TranslationLanguages,
We have a note somewhere to set up testing stuff, we could create a dev screen for things like this. I'll remove it from this PR though

2022-05-25 12:08 UTC, vanGalilea commented on examples/SampleApp/src/hooks/useChatClient.ts
> +      language: 'es' as TranslationLanguages,
I'll create an issue for this, render and copy channel id, message-id

2022-07-01 11:59 UTC, madsroskar commented
Closing this, creating a new PR

2022-07-01 11:59 UTC, closed without merging