refactor: getLatestMessageDisplayText
GetStream/stream-chat-react-native pull request #1425
Opened 2022-06-01 11:10 UTC by Enigma-I-am

## 🎯 Goal

## 🛠 Implementation details

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## 🧪 Testing

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec
- [ ] New code is covered by tests
- [ ] Screenshots added for visual changes
- [ ] Documentation is updated

2022-06-08 10:26 UTC, vanGalilea requested changes

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
> +const messageOwner = <
What does this function do? Let's give it a better name!

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +    console.log(result.current.created_at);
please remove console.log

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +    console.log(result.current.created_at);
please remove console.log

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +    console.log(result.current.created_at);
please remove console.log

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +    console.log(result.current);
please remove console.log

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  const CHANNEL_WITH_MESSAGES_TEXT = {
Please move all costs to a separate mocks file ;)

2022-06-08 10:26 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +import React, { FC } from 'react';
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=GetStream_stream-chat-react-native&pullRequest=1425)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL)
> 
> [![54.3%](https://camo.githubusercontent.com/f153f49021c687322b27f7437ddd113bb22ef96cd3bf99f2c8c8d7786d37e5ce/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f35302d313670782e706e67)](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_coverage&view=list) [54.3% Coverage](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_duplicated_lines_density&view=list)

Please increase code coverage to pass quality gate (%80)

2022-06-22 11:15 UTC, Enigma-I-am commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=GetStream_stream-chat-react-native&pullRequest=1425)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1425&resolved=false&types=CODE_SMELL)
> 
> [![94.4%](https://camo.githubusercontent.com/7241b8996b33455e2d93eace36e0fe8ca6107d0d898e03bbfecd7ee647c41751/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f39302d313670782e706e67)](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_coverage&view=list) [94.4% Coverage](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1425&metric=new_duplicated_lines_density&view=list)

@vanGalilea test coverage is now above 80%

2022-06-22 13:16 UTC, vanGalilea requested changes

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return message deleted', async () => {
This test title is incorrect right?

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return latest text', async () => {
The title of the test should be more specific, we're expecting the whole result is there.

But at the end of the day, we care about what is being rendered to the user.

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return latest text', async () => {
we say "should return latest text" if that's what you want to test, just expect `result.current.reviews` (or whatever is being rendered)

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return a channel with a mentioned user', async () => {
same for the name here, do we return a channel here or actually a message preview with a mentioned user?

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return a channel with a mentioned user', async () => {
Please be more spec. with assertion

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +          { bold: false, text: '🏙 Attachment...' },
That's what the user sees so let's only assert that, what are your thoughts on that?

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +  it('should return a channel with an empty message', async () => {
again not a channel here, let's give a test a better and realistic name

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/__tests__/useLatestMessagePreview.test.tsx
> +          { bold: false, text: '/giphy' },
let's only assert what the users sees etc

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
> +    const mentionUSerString = mentionedUser.reduce((acc, cur) => {
```suggestion
    const mentionUserString = mentionedUser.reduce((acc, cur) => {
```

2022-06-22 13:16 UTC, vanGalilea commented on package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
> +    return mentionUSerString;
```suggestion
    return mentionUserString;
```

2022-06-29 11:07 UTC, Enigma-I-am commented
@vanGalilea updates have been puushed

2022-06-29 12:27 UTC, vanGalilea approved these changes

2022-06-29 12:28 UTC, merged