feat: make react-native-share and react-native-haptic-feedback optional
GetStream/stream-chat-react-native pull request #1744
Opened 2022-09-29 16:55 UTC by madsroskar

** Draft for now, gotta write docs tommake it ready **

## 🎯 Goal

## 🛠 Implementation details

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## 🧪 Testing

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

2022-09-29 18:12 UTC, vanGalilea requested changes

2022-09-30 07:44 UTC, madsroskar commented on package/native-package/src/handlers/shareImage.ts
> +  console.log('RNShare is available');
Yeah that's an oversight while committing, removing it

2022-10-04 14:41 UTC, vishalnarkhede approved these changes

2022-10-05 09:44 UTC, vishalnarkhede commented
Nice job @madsroskar :)

2022-10-05 09:50 UTC, vanGalilea approved these changes

2022-10-05 09:52 UTC, vanGalilea approved these changes

2022-10-06 07:36 UTC, merged

2022-10-10 13:26 UTC, vishalnarkhede commented
:tada: This PR is included in version 5.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/stream-chat-react-native-core/v/5.4.0)
- [GitHub release](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: