fix: add pointerEvents to ReactionList
GetStream/stream-chat-react-native pull request #2196
Opened 2023-07-24 15:40 UTC by aharwood9

## 🎯 Goal

Currently `ReactionList` has several Views that are take up basically the full screen width. These views have a height that is based on the reactionSize. Using the default reactionSize, these take up roughly half the size of the `MessageContent` size if the message is a single line of text. 

This absolute overlay then blocks the `MessageContent` components `TouchableOpacity`. Thus, the goal is to fix #2021 by making `ReactionList` not block the `TouchableOpacity` in `MessageContent`. FYI I couldn't repo the hit box moving when adding a reaction, only the blocking of long press on both iOS and Android. 

## 🛠 Implementation details

Update the `View` and `Svg` to have `pointerEvents` that don't block the underlying `TouchableOpacity` from `MessageContnet` while maintaining the `TouchOpacity` of the `ReactionList` functionality.

## 🎨 UI Changes

<details>
<summary>iOS & Android</summary>

https://github.com/GetStream/stream-chat-react-native/assets/45667737/ed84eebd-37b7-4c38-88dd-40de4c0eac5e

</details>

## 🧪 Testing

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [x] SampleApp iOS and Android
  - [ ] Expo iOS and Android

2023-09-02 16:14 UTC, khushal87 requested changes

2023-09-02 16:14 UTC, khushal87 commented on package/src/components/Message/MessageSimple/ReactionList.tsx
> +            pointerEvents='none'
```suggestion
```

2023-09-02 16:16 UTC, khushal87 commented
Hey @aharwood9 thanks for fixing the bug. The solution works after testing. 🚀 

The only thing here is if you can remove the `pointerEvents` from the View as per suggested above. It seems unnecessary. Thanks 😄

2023-09-03 13:49 UTC, aharwood9 commented
> Hey @aharwood9 thanks for fixing the bug. The solution works after testing. 🚀
> 
> The only thing here is if you can remove the `pointerEvents` from the View as per suggested above. It seems unnecessary. Thanks 😄

Nice catch 👍 committed your suggestion

2023-09-03 15:26 UTC, merged